#ivy cached data file for org.junit.platform#junit-platform-console-standalone;1.9.3
#Fri Mar 06 07:11:48 PST 2026
artifact.resolver=main
artifact\:ivy\#ivy\#xml\#-1468383470.exists=true
artifact\:ivy\#ivy\#xml\#-1468383470.is-local=false
artifact\:ivy\#ivy\#xml\#-1468383470.location=https\://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.pom
artifact\:ivy\#ivy\#xml\#-1468383470.original=artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625
artifact\:junit-platform-console-standalone\#jar\#jar\#170028963.exists=true
artifact\:junit-platform-console-standalone\#jar\#jar\#170028963.is-local=false
artifact\:junit-platform-console-standalone\#jar\#jar\#170028963.location=https\://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
artifact\:junit-platform-console-standalone\#jar\#jar\#170028963.original=artifact\:junit-platform-console-standalone\#jar\#jar\#170028963
artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625.exists=true
artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625.is-local=false
artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625.location=https\://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.pom
artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625.original=artifact\:junit-platform-console-standalone\#pom.original\#pom\#1822591625
resolver=public
