#org#module;working@Giless-MacBook-Air.local resolved revisions
#Fri Mar 06 07:15:24 PST 2026
+organisation\:\#@\#\:+com.google.code.gson\:\#@\#\:+branch\:\#@\#\:+@\#\:NULL\:\#@\:\#@\#\:+module\:\#@\#\:+gson\:\#@\#\:+revision\:\#@\#\:+2.10.1\:\#@\#\:=2.10.1 release 2.10.1 null
