#ivy cached data file for com.google.code.gson#gson;2.10.1
#Fri Mar 06 07:15:24 PST 2026
artifact.resolver=main
artifact\:gson\#jar\#jar\#-1411245591.exists=true
artifact\:gson\#jar\#jar\#-1411245591.is-local=false
artifact\:gson\#jar\#jar\#-1411245591.location=https\://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
artifact\:gson\#jar\#jar\#-1411245591.original=artifact\:gson\#jar\#jar\#-1411245591
artifact\:gson\#pom.original\#pom\#241317071.exists=true
artifact\:gson\#pom.original\#pom\#241317071.is-local=false
artifact\:gson\#pom.original\#pom\#241317071.location=https\://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.pom
artifact\:gson\#pom.original\#pom\#241317071.original=artifact\:gson\#pom.original\#pom\#241317071
artifact\:ivy\#ivy\#xml\#-1330276597.exists=true
artifact\:ivy\#ivy\#xml\#-1330276597.is-local=false
artifact\:ivy\#ivy\#xml\#-1330276597.location=https\://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.pom
artifact\:ivy\#ivy\#xml\#-1330276597.original=artifact\:gson\#pom.original\#pom\#241317071
resolver=public
